name = "Cookbook"
defaultTargets = ["Cookbook", "lean-cookbook"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.28.0"

[[lean_lib]]
name = "Cookbook"

[[lean_exe]]
name = "lean-cookbook"
root = "Main"
